# Generated by Django 3.1.5 on 2021-05-29 19:06

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_textmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textmodel',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
