# Generated by Django 3.1.5 on 2021-05-30 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_commentmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentmodel',
            old_name='autor_person',
            new_name='author_person',
        ),
    ]
