# Generated by Django 3.1.5 on 2021-05-31 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210530_2001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentmodel',
            old_name='createdDate',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='commentmodel',
            old_name='editingDate',
            new_name='editing_date',
        ),
    ]
