# Generated by Django 3.1.5 on 2021-06-01 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210531_1907'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name_surname', models.CharField(max_length=160)),
                ('message', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Communication',
                'verbose_name_plural': 'Communication',
                'db_table': 'communication',
            },
        ),
    ]
